# Copyright (C) 2019 NXP Semiconductors, All Rights Reserved.
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

snd-soc-tfa98xx-objs := tfa_container.o tfa_dsp.o tfa_init.o tfa98xx.o
obj-y += snd-soc-tfa98xx.o